import { csvCell } from "./core.js";

const COLLECTION_KEYS = ["people", "onboarding", "tasks", "crmOwnership", "activity", "audit"];

export function createPersonDraft() {
  return {
    displayName: "",
    email: "",
    role: "intern",
    accessMethod: "invite",
    locale: "en",
    timezone: "America/New_York",
    phone: "",
    managerId: "",
    skills: "",
    availability: "",
    startDate: "",
    notes: "",
  };
}

export function filterAdministrationPeople(people, filters = {}) {
  const query = String(filters.query || "").trim().toLowerCase();
  return (people || []).filter((person) => {
    const search = [person.displayName, person.loginIdentifier, person.managerName, ...(person.skills || [])]
      .join(" ")
      .toLowerCase();
    return (!query || search.includes(query))
      && (!filters.role || filters.role === "all" || person.role === filters.role)
      && (!filters.status || filters.status === "all" || person.membershipStatus === filters.status);
  });
}

function parseDelimited(text) {
  const source = String(text || "").replace(/^\uFEFF/, "");
  const rows = [];
  let row = [];
  let cell = "";
  let quoted = false;
  for (let index = 0; index < source.length; index += 1) {
    const character = source[index];
    if (character === '"') {
      if (quoted && source[index + 1] === '"') {
        cell += '"';
        index += 1;
      } else quoted = !quoted;
    } else if (character === "," && !quoted) {
      row.push(cell);
      cell = "";
    } else if ((character === "\n" || character === "\r") && !quoted) {
      if (character === "\r" && source[index + 1] === "\n") index += 1;
      row.push(cell);
      if (row.some(Boolean)) rows.push(row);
      row = [];
      cell = "";
    } else cell += character;
  }
  row.push(cell);
  if (row.some(Boolean)) rows.push(row);
  return rows;
}

function normalizePackage(input) {
  if (!input || typeof input !== "object" || Array.isArray(input)) throw new Error("The administration package must be an object.");
  if (Number(input.schemaVersion) !== 1) throw new Error("This administration schema version is not supported.");
  const result = { ...input };
  for (const key of COLLECTION_KEYS) {
    if (result[key] !== undefined && !Array.isArray(result[key])) throw new Error(`Administration ${key} must be an array.`);
  }
  return result;
}

function markdownCell(value) {
  return String(value ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function encodeBase64(value) {
  const bytes = new globalThis.TextEncoder().encode(value);
  let binary = "";
  for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000));
  return globalThis.btoa(binary);
}

function decodeBase64(value) {
  const binary = globalThis.atob(value.replace(/\s+/g, ""));
  const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
  return new globalThis.TextDecoder().decode(bytes);
}

export async function buildAdministrationExport(input, format) {
  const data = normalizePackage(structuredClone(input));
  if (format === "json") {
    return { extension: "json", mime: "application/json", content: JSON.stringify(data, null, 2) };
  }
  if (format === "csv") {
    const collectionKeys = COLLECTION_KEYS.filter((key) => Array.isArray(data[key]));
    const metadata = Object.fromEntries(Object.entries(data).filter(([key]) => !COLLECTION_KEYS.includes(key)));
    metadata.collectionKeys = collectionKeys;
    const records = [["__package__", "manifest", metadata]];
    for (const key of collectionKeys) {
      for (const [index, value] of data[key].entries()) records.push([key, value.id || value.userId || `${key}-${index + 1}`, value]);
    }
    const lines = ["record_type,record_id,payload_json", ...records.map((record) => record.map((value) => csvCell(typeof value === "string" ? value : JSON.stringify(value))).join(","))];
    return { extension: "csv", mime: "text/csv;charset=utf-8", content: `\uFEFF${lines.join("\r\n")}` };
  }
  if (format === "md") {
    const people = data.people.map((person) => `| ${markdownCell(person.displayName)} | ${markdownCell(person.role?.replace(/^./, (letter) => letter.toUpperCase()))} | ${markdownCell(person.membershipStatus?.replace(/^./, (letter) => letter.toUpperCase()))} |`).join("\n");
    const content = `# AOI Administration Archive\n\nSchema version: ${data.schemaVersion}  \nExported: ${data.exportedAt || "Not recorded"}\n\n## People\n\n| Person | Role | Status |\n| --- | --- | --- |\n${people || "| No people |  |  |"}\n\n## Restore data\n\nThe block below is generated by Ambiloop Ops. Keep it unchanged for re-import.\n\n\`\`\`aoi-administration-base64\n${encodeBase64(JSON.stringify(data))}\n\`\`\`\n`;
    return { extension: "md", mime: "text/markdown;charset=utf-8", content };
  }
  throw new Error(`Unsupported administration format: ${format}`);
}

export async function parseAdministrationImport(content, format) {
  if (format === "json") {
    try {
      return normalizePackage(JSON.parse(String(content || "")));
    } catch (reason) {
      if (reason instanceof Error && reason.message.includes("administration")) throw reason;
      throw new Error("Upload valid JSON generated by AOI Administration.");
    }
  }
  if (format === "csv") {
    const rows = parseDelimited(content);
    if (rows[0]?.join(",") !== "record_type,record_id,payload_json") throw new Error("Upload a generated AOI administration CSV.");
    const manifestRow = rows.find((row) => row[0] === "__package__");
    if (!manifestRow) throw new Error("The AOI administration CSV manifest is missing.");
    let manifest;
    try {
      manifest = JSON.parse(manifestRow[2]);
    } catch {
      throw new Error("The AOI administration CSV manifest is invalid.");
    }
    const collectionKeys = Array.isArray(manifest.collectionKeys) ? manifest.collectionKeys : [];
    delete manifest.collectionKeys;
    const data = { ...manifest };
    for (const key of collectionKeys) {
      if (!COLLECTION_KEYS.includes(key)) throw new Error(`Unsupported administration collection: ${key}`);
      data[key] = rows.filter((row) => row[0] === key).map((row) => JSON.parse(row[2]));
    }
    return normalizePackage(data);
  }
  if (format === "md") {
    const match = String(content || "").match(/```aoi-administration-base64\s*([a-z0-9+/=\s]+)```/i);
    if (!match) throw new Error("Upload a generated AOI administration Markdown archive.");
    try {
      return normalizePackage(JSON.parse(decodeBase64(match[1])));
    } catch (reason) {
      if (reason instanceof Error && reason.message.includes("administration")) throw reason;
      throw new Error("The generated AOI administration Markdown data is invalid.");
    }
  }
  throw new Error(`Unsupported administration format: ${format}`);
}
