export const fallbackDashboard = {
  organization: {
    id: "demo-org",
    name: "HUGE DENTAL USA LLC / AOI Technologics",
    slug: "aoi-technologics",
  },
  project: {
    id: "demo-project",
    code: "AOI-PMF-01",
    name: "Ambiloop U.S. PMF Validation",
    description: "Bilingual research operations, evidence traceability, and GTM validation.",
    currentWeek: 4,
    startDate: "2026-07-13",
    endDate: "2026-09-25",
  },
  metrics: [
    { key: "weekly_plan", label: "Weekly plan", value: 72, target: 100, unit: "percent", delta: 8 },
    { key: "evidence_records", label: "Evidence records", value: 168, target: 200, unit: "number", delta: 24 },
    { key: "pending_reviews", label: "Pending reviews", value: 3, target: 0, unit: "number", delta: 1 },
    { key: "active_blockers", label: "Active blockers", value: 2, target: 0, unit: "number", delta: -1 },
  ],
  tasks: [
    { id: "t1", title: "Synthesize pediatric dentist interviews", objective: "Convert eight conversations into traceable Need Truth evidence.", status: "in_progress", priority: "high", ownerName: "Kayla Tillmon", ownerInitials: "KT", dueDate: "2026-08-04", pmfLayer: "Need Truth", progress: 68, points: 180 },
    { id: "t2", title: "Review recruitment message v3", objective: "Approve language before the next clinician outreach wave.", status: "submitted", priority: "critical", ownerName: "Ethan", ownerInitials: "ET", dueDate: "2026-08-03", pmfLayer: "Need Truth", progress: 100, points: 120 },
    { id: "t3", title: "Log orthodontic solution-gap evidence", objective: "Add supporting and contradictory quotes with strength scores.", status: "revision_requested", priority: "high", ownerName: "Wen Tang", ownerInitials: "WT", dueDate: "2026-08-03", pmfLayer: "Solution Gap", progress: 54, points: 160 },
    { id: "t4", title: "Schedule implant-maintenance interviews", objective: "Book the remaining two qualified periodontists.", status: "blocked", priority: "medium", ownerName: "Mike Revou Moses", ownerInitials: "MR", dueDate: "2026-08-05", pmfLayer: "Need Truth", progress: 40, points: 140 },
    { id: "t5", title: "Prepare Week 4 evidence review", objective: "Summarize learning, limitations, and the recommended next action.", status: "assigned", priority: "high", ownerName: "Zhen", ownerInitials: "ZH", dueDate: "2026-08-06", pmfLayer: "Product Value", progress: 12, points: 220 },
    { id: "t6", title: "Validate concept-test survey logic", objective: "Check segment quotas, Gabor-Granger branching, and consent.", status: "approved", priority: "medium", ownerName: "Administrator", ownerInitials: "AD", dueDate: "2026-08-02", pmfLayer: "Value Exchange", progress: 100, points: 200 },
  ],
  samplePlan: [
    { id: "s1", label: "Dental professionals", pmfLayer: "Need Truth", actual: 19, target: 35, accent: "orange" },
    { id: "s2", label: "Consumer interviews", pmfLayer: "Need Truth", actual: 24, target: 40, accent: "teal" },
    { id: "s3", label: "Concept-test responses", pmfLayer: "Product Value", actual: 86, target: 200, accent: "blue" },
    { id: "s4", label: "Product test users", pmfLayer: "Repeatability", actual: 8, target: 32, accent: "purple" },
  ],
  pmfLayers: [
    { id: "p1", code: "H1", name: "Need Truth", sequence: 1, confidence: 78, status: "provisional", evidenceCount: 54, counterevidenceCount: 8, nextAction: "Close the pediatric dentist evidence gap" },
    { id: "p2", code: "H2", name: "Current Solution Gap", sequence: 2, confidence: 64, status: "partial", evidenceCount: 41, counterevidenceCount: 12, nextAction: "Verify switching readiness by segment" },
    { id: "p3", code: "H3", name: "Product Value", sequence: 3, confidence: 46, status: "not_validated", evidenceCount: 28, counterevidenceCount: 7, nextAction: "Complete the concept-test sample" },
    { id: "p4", code: "H4", name: "Repeatability", sequence: 4, confidence: 22, status: "not_validated", evidenceCount: 11, counterevidenceCount: 4, nextAction: "Begin four-week home-use cohort" },
    { id: "p5", code: "H5", name: "Value Exchange", sequence: 5, confidence: 18, status: "not_validated", evidenceCount: 7, counterevidenceCount: 3, nextAction: "Launch price and commitment test" },
  ],
  segments: [
    { id: "seg-1", code: "families", name: "Families with Children", audienceType: "consumer" },
    { id: "seg-2", code: "orthodontic", name: "Adult Orthodontic Patients", audienceType: "consumer" },
    { id: "seg-3", code: "pediatric-dentist", name: "Pediatric Dentists", audienceType: "professional" },
  ],
  respondents: [
    { id: "resp-1", externalId: "R-FAM-014", segmentCode: "families", segmentName: "Families with Children", respondentType: "Consumer", consentStatus: "granted", status: "active", workflowStatus: "approved", assignedToName: "Kayla Tillmon", createdAt: "2026-08-01T13:00:00.000Z" },
    { id: "resp-2", externalId: "R-ORTH-006", segmentCode: "orthodontic", segmentName: "Adult Orthodontic Patients", respondentType: "Consumer", consentStatus: "granted", status: "active", workflowStatus: "approved", assignedToName: "Wen Tang", createdAt: "2026-08-01T15:00:00.000Z" },
    { id: "resp-3", externalId: "R-PED-009", segmentCode: "pediatric-dentist", segmentName: "Pediatric Dentists", respondentType: "Dental Professional", consentStatus: "pending", status: "scheduled", workflowStatus: "submitted", assignedToName: "Kayla Tillmon", createdAt: "2026-08-03T10:00:00.000Z" },
  ],
  sessions: [
    { id: "session-1", respondentId: "resp-1", segmentCode: "families", pmfLayer: "H1", method: "JTBD interview", sessionDate: "2026-08-02", unmetNeed: "Know whether a visible change needs action before the next visit.", workflowStatus: "approved", assignedToName: "Kayla Tillmon", createdAt: "2026-08-02T16:00:00.000Z" },
  ],
  evidence: [
    { id: "pmf-e1", respondentId: "resp-1", sessionId: "session-1", segmentCode: "families", pmfLayer: "H1", dimension: "Frequency", title: "Caregivers notice changes between visits", evidenceText: "Recent changes prompted photos and online searches.", stance: "supporting", strength: 3, limitations: "Single recruited caregiver segment.", consentStatus: "granted", workflowStatus: "approved", assignedToName: "Kayla Tillmon", createdAt: "2026-08-02T16:30:00.000Z" },
    { id: "pmf-e2", respondentId: "resp-2", segmentCode: "orthodontic", pmfLayer: "H1", dimension: "Actionability", title: "Some changes still require a clinician", evidenceText: "The respondent could see a change but could not choose an action.", stance: "contradicting", strength: 3, limitations: "One orthodontic participant.", consentStatus: "granted", workflowStatus: "approved", assignedToName: "Wen Tang", createdAt: "2026-08-02T18:00:00.000Z" },
  ],
  productEvents: [],
  valueExchange: [],
  definitions: [
    { id: "def-h1", code: "recent_change_rate", layer: "H1", dimension: "Frequency", label: "Experienced a target change in six months", valueType: "boolean", unit: "percent" },
    { id: "def-h2", code: "switching_readiness", layer: "H2", dimension: "Switching Readiness", label: "Willingness to try a new solution", valueType: "numeric", unit: "score" },
    { id: "def-h3", code: "capture_success", layer: "H3", dimension: "Capture", label: "First independent capture success", valueType: "boolean", unit: "percent" },
    { id: "def-h4", code: "week_4_reuse", layer: "H4", dimension: "Actual Reuse", label: "Week 4 reuse", valueType: "boolean", unit: "percent" },
    { id: "def-h5", code: "purchase_intent_259", layer: "H5", dimension: "Price Acceptance", label: "Purchase intent at $259", valueType: "numeric", unit: "score" },
  ],
  observations: [
    { id: "obs-1", definitionId: "def-h1", respondentId: "resp-1", segmentCode: "families", booleanValue: true, workflowStatus: "approved", assignedToName: "Kayla Tillmon", createdAt: "2026-08-02T17:00:00.000Z" },
    { id: "obs-2", definitionId: "def-h1", respondentId: "resp-2", segmentCode: "orthodontic", booleanValue: true, workflowStatus: "approved", assignedToName: "Wen Tang", createdAt: "2026-08-02T18:15:00.000Z" },
    { id: "obs-3", definitionId: "def-h2", respondentId: "resp-1", segmentCode: "families", numericValue: 4, workflowStatus: "approved", assignedToName: "Kayla Tillmon", createdAt: "2026-08-02T18:30:00.000Z" },
  ],
  hypotheses: [],
  reviewQueue: [
    { id: "resp-3", recordType: "respondent", title: "R-PED-009", workflowStatus: "submitted", submittedAt: "2026-08-03T10:05:00.000Z", assignedToName: "Kayla Tillmon" },
  ],
  gateSnapshots: [],
  activity: [
    { id: "a1", actorName: "Ethan", actorInitials: "ET", action: "submitted", subject: "Recruitment message v3", eventType: "review", occurredAt: "2026-08-03T18:42:00.000Z" },
    { id: "a2", actorName: "Kayla Tillmon", actorInitials: "KT", action: "logged 6 evidence records", subject: "Pediatric dentist interviews", eventType: "evidence", occurredAt: "2026-08-03T18:00:00.000Z" },
    { id: "a3", actorName: "Wen Tang", actorInitials: "WT", action: "received revision feedback", subject: "Orthodontic solution-gap evidence", eventType: "revision", occurredAt: "2026-08-03T16:00:00.000Z" },
    { id: "a4", actorName: "Mike Revou Moses", actorInitials: "MR", action: "flagged a blocker", subject: "Implant-maintenance recruitment", eventType: "blocked", occurredAt: "2026-08-03T14:00:00.000Z" },
  ],
  signals: [
    { id: "r1", theme: "Caregiver visibility between visits", stance: "supporting", evidenceCount: 31, changePercent: 18, strength: 3.4 },
    { id: "r2", theme: "Image-comparison confidence", stance: "supporting", evidenceCount: 24, changePercent: 12, strength: 3.1 },
    { id: "r3", theme: "Actionability without clinician context", stance: "contradicting", evidenceCount: 14, changePercent: 7, strength: 2.8 },
    { id: "r4", theme: "Routine-fit friction", stance: "contradicting", evidenceCount: 9, changePercent: 3, strength: 2.4 },
  ],
  team: [
    { id: "m1", displayName: "Kayla Tillmon", initials: "KT", roleLabel: "Research Intern", points: 1480, weeklyPoints: 340, streakDays: 6, completedTasks: 12, rank: 1 },
    { id: "m2", displayName: "Wen Tang", initials: "WT", roleLabel: "Research Intern", points: 1320, weeklyPoints: 280, streakDays: 4, completedTasks: 11, rank: 2 },
    { id: "m3", displayName: "Mike Revou Moses", initials: "MR", roleLabel: "Doctor BD Support", points: 1180, weeklyPoints: 220, streakDays: 3, completedTasks: 9, rank: 3 },
  ],
  campaign: {
    name: "August KOL Outreach",
    deadline: "2026-08-20",
    targetLow: 40,
    targetHigh: 50,
    planningTarget: 45,
    conversionRate: 0.4,
  },
  outreachSummary: {
    totalCandidates: 70,
    contactReady: 61,
    contacted: 11,
    responses: 0,
    interested: 0,
    confirmed: 0,
    pmfCandidates: 32,
    researchNeeded: 9,
  },
  categories: [
    { name: "Dental Professional", candidates: 49, contactReady: 48, confirmed: 0 },
    { name: "Mom & Family", candidates: 10, contactReady: 7, confirmed: 0 },
    { name: "Technology Reviewer", candidates: 8, contactReady: 5, confirmed: 0 },
    { name: "Other / Discovery", candidates: 3, contactReady: 1, confirmed: 0 },
  ],
  candidates: [
    { id: "c1", externalId: "1", name: "@thebentist", category: "Dental Professional", platforms: "TikTok", reach: "15.9M", tier: "Mega", fitLevel: "High", contactReadiness: "Social DM ready", pmfCandidate: true, ownerName: "Mike", priorityScore: 82, priorityBand: "High", outreachStatus: "Sent", interestLevel: "Unknown", nextStep: "Follow up and request rate card", nextStepDue: "2026-08-07", sourceUrl: "https://www.tiktok.com/@thebentist", firstOutreach: "2026-08-03", lastUpdated: "2026-08-03", notes: "Asked for collaboration pricing, formats, contact information, availability, and PMF validation interest." },
    { id: "c2", externalId: "3", name: "@jasminerdh", category: "Dental Professional", platforms: "TikTok / YouTube", reach: "1.1M", tier: "Mega", fitLevel: "High", contactReadiness: "Email ready", pmfCandidate: false, ownerName: "Mike", priorityScore: 80, priorityBand: "High", outreachStatus: "Sent", interestLevel: "Unknown", nextStep: "Follow up and request rate card", nextStepDue: "2026-08-07", sourceUrl: "https://www.tiktok.com/@jasminerdh", firstOutreach: "2026-08-03", lastUpdated: "2026-08-03", notes: "Product reviews and dental hygiene education." },
    { id: "c3", externalId: "8", name: "@askthedentist", category: "Dental Professional", platforms: "TikTok / YouTube", reach: "385K", tier: "Macro", fitLevel: "Medium", contactReadiness: "Email ready", pmfCandidate: true, ownerName: "Mike", priorityScore: 94, priorityBand: "High", outreachStatus: "Sent", interestLevel: "Unknown", nextStep: "Follow up and ask for call availability", nextStepDue: "2026-08-07", sourceUrl: "https://www.tiktok.com/@askthedentist", firstOutreach: "2026-08-03", lastUpdated: "2026-08-03", notes: "Evidence-based dentistry and oral microbiome audience." },
    { id: "c4", externalId: "12", name: "@dentist_emi", category: "Dental Professional", platforms: "TikTok / Instagram / YouTube", reach: "93K", tier: "Micro", fitLevel: "High", contactReadiness: "Unreachable via current social routes", pmfCandidate: true, ownerName: "Kayla Tillmon", priorityScore: 80, priorityBand: "High", outreachStatus: "Unreachable", interestLevel: "Unknown", nextStep: "Find alternate verified contact route", nextStepDue: "2026-08-04", sourceUrl: "https://www.tiktok.com/@dentist_emi", firstOutreach: "2026-08-03", lastUpdated: "2026-08-03", notes: "Instagram messages blocked; TikTok unavailable." },
    { id: "c5", externalId: "51", name: "@bracesbybritt / Dr. Britteny Zito", category: "Dental Professional", platforms: "Instagram / TikTok / YouTube", reach: "1M+", tier: "Macro", fitLevel: "High", contactReadiness: "Form ready", pmfCandidate: true, ownerName: "Kayla Tillmon", priorityScore: 95, priorityBand: "High", outreachStatus: "Ready to Send", interestLevel: "Unknown", nextStep: "Personalize and send first touch", nextStepDue: "2026-08-05", sourceUrl: "https://www.bracesbybritt.com/", lastUpdated: "2026-08-03", notes: "Strong orthodontic education and hands-on feedback fit." },
    { id: "c6", externalId: "53", name: "The Peds Dentist / Dr. Ivy Fua", category: "Dental Professional", platforms: "Website / social", reach: "Not verified", tier: "Professional KOL", fitLevel: "High", contactReadiness: "Form ready", pmfCandidate: true, ownerName: "Wen Tang", priorityScore: 97, priorityBand: "High", outreachStatus: "Ready to Send", interestLevel: "Unknown", nextStep: "Personalize and send first touch", nextStepDue: "2026-08-05", sourceUrl: "https://www.thepedsdentist.com/contact", lastUpdated: "2026-08-03", notes: "Pediatric and parent crossover; strong PMF interview candidate." },
    { id: "c7", externalId: "58", name: "One Messy Mama / Ashton", category: "Mom & Family", platforms: "Blog / Instagram / Facebook / Pinterest", reach: "Not verified", tier: "Micro", fitLevel: "High", contactReadiness: "Email ready", pmfCandidate: false, ownerName: "Kayla Tillmon", priorityScore: 85, priorityBand: "High", outreachStatus: "Ready to Send", interestLevel: "Unknown", nextStep: "Personalize family collaboration email", nextStepDue: "2026-08-06", sourceUrl: "https://onemessymama.com/contact-me/", lastUpdated: "2026-08-03", notes: "Open to authentic family brand collaborations." },
    { id: "c8", externalId: "64", name: "Well Connected Mom / Lori", category: "Technology Reviewer", platforms: "Blog / social", reach: "Not verified", tier: "Publisher", fitLevel: "High", contactReadiness: "Email ready", pmfCandidate: false, ownerName: "Wen Tang", priorityScore: 78, priorityBand: "Medium", outreachStatus: "Ready to Send", interestLevel: "Unknown", nextStep: "Send independent review pitch", nextStepDue: "2026-08-07", sourceUrl: "https://wellconnectedmom.com/blog/contact-us/", lastUpdated: "2026-08-03", notes: "Bridge between family use and technology review." },
    { id: "c9", externalId: "44", name: "@Nano Pool A", category: "Dental Professional", platforms: "TikTok / Instagram", reach: "1K-10K", tier: "Nano", fitLevel: "Medium", contactReadiness: "Research needed", pmfCandidate: false, ownerName: "Kayla Tillmon", priorityScore: 52, priorityBand: "Low", outreachStatus: "Not Contacted", interestLevel: "Unknown", nextStep: "Find verified business contact", nextStepDue: "2026-08-06", sourceUrl: "https://www.tiktok.com/", lastUpdated: "2026-08-03", notes: "Search via #dentalhygienist." },
    { id: "c10", externalId: "69", name: "TechRadar Health & Fitness", category: "Technology Reviewer", platforms: "Website / YouTube / social", reach: "Not verified", tier: "Publisher", fitLevel: "High", contactReadiness: "Research needed", pmfCandidate: false, ownerName: "Wen Tang", priorityScore: 53, priorityBand: "Low", outreachStatus: "Not Contacted", interestLevel: "Unknown", nextStep: "Route to the correct health editor", nextStepDue: "2026-08-08", sourceUrl: "https://www.techradar.com/health-fitness/oral-health/best-electric-toothbrush", lastUpdated: "2026-08-03", notes: "Direct oral-care technology review relevance." },
  ],
  outreachEvents: [
    { id: "o1", candidateId: "c1", channel: "Email", kind: "Initial", status: "Sent", occurredAt: "2026-08-03T10:00:00.000Z", actorName: "Mike", summary: "Deck introduced and PMF conversation requested." },
    { id: "o2", candidateId: "c1", channel: "TikTok DM", kind: "Initial", status: "Sent", occurredAt: "2026-08-03T10:04:00.000Z", actorName: "Mike", summary: "Asked for the best business email." },
    { id: "o3", candidateId: "c4", channel: "Instagram", kind: "Attempt", status: "Blocked", occurredAt: "2026-08-03T11:00:00.000Z", actorName: "Kayla Tillmon", summary: "Messaging unavailable; alternate contact required." },
  ],
  evidenceRecords: [
    { id: "e1", candidateId: "c1", type: "PMF interview", stance: "supporting", strength: 3, title: "Visibility between visits is a recurring caregiver concern", recordedBy: "Mike", recordedAt: "2026-08-03", consentStatus: "pending", notes: "Discovery conversation only; not clinical evidence." },
    { id: "e2", candidateId: "c4", type: "Contact research", stance: "contradicting", strength: 2, title: "Current social routes are blocked", recordedBy: "Kayla Tillmon", recordedAt: "2026-08-03", consentStatus: "not_applicable", notes: "Do not retry blocked channels without a new route." },
  ],
  recommendations: [
    { id: "pool-gap", type: "pipeline", priority: "critical", title: "Rebuild the active prospect pool", reason: "113 active prospects are needed at the assumed 40% conversion rate; the current pool has 70.", action: "Add 43 qualified prospects before sending the next wave." },
    { id: "confirmation-gap", type: "deadline", priority: "critical", title: "Protect the confirmation deadline", reason: "40 low-target confirmations are still missing for 2026-08-20.", action: "Prioritize high-score, contact-ready candidates and assign a dated follow-up." },
    { id: "category-Mom & Family", type: "category", priority: "high", title: "Enrich Mom & Family coverage", reason: "3 records in this category still need a verified contact route.", action: "Assign contact research and require a source URL before outreach." },
  ],
  generatedAt: "2026-08-03T19:00:00.000Z",
};

fallbackDashboard.crmContacts = fallbackDashboard.candidates.map((candidate) => ({
  id: `crm-${candidate.id}`,
  candidateId: candidate.id,
  contactType: candidate.category,
  name: candidate.name,
  organization: "",
  email: candidate.contactDetail || "",
  phone: "",
  primaryChannel: candidate.contactChannel || (candidate.platforms?.split(" /")[0] || "Email"),
  sourceUrl: candidate.sourceUrl,
  tags: candidate.pmfCandidate ? "PMF candidate" : "",
  ownerName: candidate.ownerName,
  lifecycle: ["Confirmed"].includes(candidate.outreachStatus) ? "qualified" : ["Interested", "Replied"].includes(candidate.outreachStatus) ? "engaged" : ["Sent", "Drafted"].includes(candidate.outreachStatus) ? "contacted" : ["Email ready", "Form ready", "Social DM ready"].includes(candidate.contactReadiness) ? "ready" : "researching",
  nextAction: candidate.nextStep,
  nextActionDue: candidate.nextStepDue,
  priorityScore: candidate.priorityScore,
  notes: candidate.notes,
  outreachStatus: candidate.outreachStatus,
  category: candidate.category,
  pmfCandidate: candidate.pmfCandidate,
  activityCount: fallbackDashboard.outreachEvents.filter((event) => event.candidateId === candidate.id).length,
}));

fallbackDashboard.crmActivity = fallbackDashboard.outreachEvents.map((event) => ({
  id: `crm-activity-${event.id}`,
  contactId: `crm-${event.candidateId}`,
  activityType: "outreach",
  summary: event.summary,
  actorName: event.actorName,
  createdAt: event.occurredAt,
}));

fallbackDashboard.crmProgress = { xp: 460, completedToday: 2, streakDays: 6 };

function previewEodRecord(values) {
  return {
    projectId: fallbackDashboard.project.id,
    projectCode: fallbackDashboard.project.code,
    projectName: fallbackDashboard.project.name,
    engagementManagerId: "preview-admin",
    engagementManagerName: "AOI Administrator",
    personInChargeId: values.authorId,
    personInChargeName: values.authorName,
    movedOutcome: "Moved one defined research outcome into review.",
    evidenceGathered: "Linked source notes and the updated evidence log.",
    deliverablesCompleted: "Daily synthesis and owner handoff.",
    keyInsight: "The next action is clearer when evidence and limitations travel together.",
    currentBlocker: "None",
    blockerImpact: "None",
    proposedSolution: "None",
    executiveOwners: ["None"],
    executiveRequest: "None",
    tomorrowPriorities: ["Close the highest-priority follow-up", "Update the evidence trail", "Prepare the next owner handoff"],
    projectStatus: "on_track",
    evidenceLinks: [{ sourceType: "evidence_log", label: "Daily evidence log", url: "https://example.com/aoi/evidence" }],
    submittedAt: "2026-08-04T20:40:00.000Z",
    isLate: false,
    updatedAt: "2026-08-04T20:40:00.000Z",
    auditHistory: [],
    ...values,
  };
}

fallbackDashboard.dailyEodReportItems = [
  previewEodRecord({ id: "eod-kayla-0804", briefDate: "2026-08-04", authorId: "m1", authorName: "Kayla Tillmon", authorRole: "intern", workflowStatus: "submitted" }),
  previewEodRecord({ id: "eod-wen-0804", briefDate: "2026-08-04", authorId: "m2", authorName: "Wen Tang", authorRole: "intern", workflowStatus: "completed", completedBy: "preview-admin", completedByName: "AOI Administrator", completedAt: "2026-08-04T20:55:00.000Z" }),
  previewEodRecord({ id: "eod-admin-0804", briefDate: "2026-08-04", authorId: "preview-admin", authorName: "AOI Administrator", authorRole: "admin", workflowStatus: "draft", submittedAt: null, movedOutcome: "", evidenceGathered: "", deliverablesCompleted: "", keyInsight: "", currentBlocker: "", blockerImpact: "", proposedSolution: "", executiveOwners: [], executiveRequest: "", evidenceLinks: [{ sourceType: "onedrive", label: "", url: "" }] }),
  previewEodRecord({ id: "eod-admin-0803", briefDate: "2026-08-03", authorId: "preview-admin", authorName: "AOI Administrator", authorRole: "admin", workflowStatus: "completed", completedBy: "preview-admin", completedByName: "AOI Administrator", completedAt: "2026-08-03T21:00:00.000Z" }),
];

fallbackDashboard.dailyEod = {
  serverDate: "2026-08-04",
  serverNow: "2026-08-04T20:45:00.000Z",
  timezone: "America/New_York",
  isWorkday: true,
  dueAt: "2026-08-04T21:00:00.000Z",
  dueState: "due",
  myBrief: null,
  members: [
    { userId: "preview-admin", displayName: "AOI Administrator", role: "admin" },
    { userId: "m1", displayName: "Kayla Tillmon", role: "intern" },
    { userId: "m2", displayName: "Wen Tang", role: "intern" },
    { userId: "m3", displayName: "Mike Revou Moses", role: "intern" },
  ],
  teamToday: [
    { userId: "preview-admin", displayName: "AOI Administrator", role: "admin", briefId: "eod-admin-0804", workflowStatus: "draft", brief: fallbackDashboard.dailyEodReportItems[2], submittedAt: null, isLate: false, projectStatus: null, updatedAt: "2026-08-04T20:10:00.000Z" },
    { userId: "m1", displayName: "Kayla Tillmon", role: "intern", briefId: "eod-kayla-0804", workflowStatus: "submitted", brief: fallbackDashboard.dailyEodReportItems[0], submittedAt: "2026-08-04T20:40:00.000Z", isLate: false, projectStatus: "on_track", updatedAt: "2026-08-04T20:40:00.000Z" },
    { userId: "m2", displayName: "Wen Tang", role: "intern", briefId: "eod-wen-0804", workflowStatus: "completed", brief: fallbackDashboard.dailyEodReportItems[1], submittedAt: "2026-08-04T20:35:00.000Z", isLate: false, projectStatus: "on_track", updatedAt: "2026-08-04T20:55:00.000Z" },
    { userId: "m3", displayName: "Mike Revou Moses", role: "intern", briefId: null, workflowStatus: "missing", brief: null, submittedAt: null, isLate: false, projectStatus: null, updatedAt: null },
  ],
};
